### ISSUE TITLE
work with eclipse?

### ISSUE THREAD

**Issue by saw07** [svendvd/Fontinator#4]
work with eclipse?

**Comment by svendvd** [comment]
Yes, you can import the Sourcecode as a libary

**Comment by saw07** [comment]
Date: Mon, 17 Aug 2015 04:42:40 -0700

**Comment by saw07** [comment]
the pic not appears before 4 min

hi i get this when i try import
![default](https://cloud.githubusercontent.com/assets/10186655/9304394/6ccaf584-44f0-11e5-81ee-59c5534c537d.png)
